variant: fcos
version: 1.2.0
passwd:
  users:
    - name: core
      # password_hash: "$6$Q7Gc4DAO3Mbkp.1X$CzWKpB1VCWzpwhHnpnUW9cvqd3Sz2SCykup1CHR9ZODRN7Qjjz8qtJb5cP9Mm6.F9c9Z1LkjZ13aQBdXKtfWP0"
      password_hash: "$6$aG07kdoNAi3I5em9$mKduVO9y12XaPnQBK29PtukOfLpim.TcmkPchE7vW4sU7sRF3GMR1tsen7wUVBgse2rVl7SZqe1T6j9JfS8mf."

      # password = hogehoge
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC94b4KKLKujeOsiTiQcQt7n7bJdR8OSL8TlTJAarVr06L+JIVq85MvXyGWmfXKxnNAbFBgLk63DoFTgFSO2RaYQmvgUNbjRpPPAfbUYJip2W21U7AhQWtF8w0xLweICZvN38dJEITzO1NljNXLI1HsG4aemXoD6J5oQfwqebwWeUMdCP7v6TpDOq7XKpNuYu/kbU3VI+gdrqHeR1HNPzsiwwizWOPFA/vDoIxoSFSwQ2niyCjVI64fRzfJaRaY98s1N1boX8ivCxNtkfqO6V47MBOFUSn63sw5x7DAUkSxLmGs8qq+G1w/ZXfpzQk2S+2lnpOrybZfiBPuHRHmwy5P/2Oaj7OAq4jzrOggSKMQiOJMZ++z+9itCdsqFf1oFh7y337/EIx3tDNok9F106CRi0T9+x1xAxTea7VfD7A22tYnDjrVJlxVO5EsmanBEFMJ/cTTEJQMpoSDIcUgyRNCQHnr/K+EuY1PeAYcZkieG46gOBXLUn9R+o0m4R1eqMeI3wlEYhLJeZCOUihiwTlnzAhKtzkeFTPNpZEEkEtFPGwS9ujDysjSx2tXxxCGALG+obg5T5awvzhQq8KMe7cs/Xa1ctaMc/1FAyYGvC8EtYiBCCR1/vgGtP1EQYMRp5FGvqNLgXIAA5lkdzd0BYAY6YUziLgTC1/uoJXw+qPE3Q=="
      # passphrase = system
      groups: [ sudo, docker ]
